"""
TheHive case-creation adapter.

Creates a TheHive 5 case from a RECON investigation, attaching all
extracted IOCs as Observables. TheHive's REST API v1 accepts:

  POST /api/v1/case  → create case
  POST /api/v1/case/{id}/observable → attach observable

This module talks to that API directly via aiohttp — TheHive's
official Python clients are GPL-3 or LGPL-3 depending on version and
we'd rather not pull a copyleft dependency. Operator configures:

  THEHIVE_URL    — https://thehive.example.org
  THEHIVE_KEY    — API key
  THEHIVE_ORG    — organisation name (TheHive 5 multi-tenant)
  THEHIVE_TLP    — default TLP for created cases (0-3, default 2=AMBER)

Returns {ok, case_id, case_number, url, observable_count, error}.
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List, Optional

_log = logging.getLogger("recon.intel.thehive_push")


# Map RECON verdict tier → TheHive severity. TheHive severity is 1-4.
_VERDICT_TO_SEVERITY = {
    "MALICIOUS":   3,
    "SUSPICIOUS":  2,
    "CLEAN":       1,
    "CLEAN_INFRA": 1,
    "UNKNOWN":     1,
}

# Map IOC type → TheHive Observable dataType. The names match TheHive 5
# defaults; custom dataTypes registered by the operator will still work
# but require the operator to align them with RECON's spelling.
_IOC_TYPE_TO_TH = {
    "ips":     "ip",
    "domains": "domain",
    "urls":    "url",
    "hashes":  "hash",
    "emails":  "mail",
    "cves":    "other",
}


def _config_or_none(config: Optional[Dict[str, Any]] = None) -> Optional[Dict[str, str]]:
    cfg: Dict[str, str] = {}
    if isinstance(config, dict):
        for k in ("THEHIVE_URL", "THEHIVE_KEY", "THEHIVE_ORG", "THEHIVE_TLP"):
            v = config.get(k)
            if v:
                cfg[k] = str(v)
    if not cfg.get("THEHIVE_URL"):
        try:
            from config import config as _cm
            for k in ("THEHIVE_URL", "THEHIVE_KEY", "THEHIVE_ORG", "THEHIVE_TLP"):
                v = _cm.get(k)
                if v and not cfg.get(k):
                    cfg[k] = str(v)
        except Exception:
            pass
    for k in ("THEHIVE_URL", "THEHIVE_KEY", "THEHIVE_ORG", "THEHIVE_TLP"):
        if not cfg.get(k):
            v = os.environ.get(k)
            if v:
                cfg[k] = v
    if not cfg.get("THEHIVE_URL") or not cfg.get("THEHIVE_KEY"):
        return None
    cfg.setdefault("THEHIVE_TLP", "2")
    return cfg


def _flatten_observables(iocs: Dict[str, List[str]],
                         tlp: int) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for ioc_type, values in (iocs or {}).items():
        data_type = _IOC_TYPE_TO_TH.get(ioc_type)
        if not data_type or not isinstance(values, list):
            continue
        for v in values[:60]:
            if not isinstance(v, str) or not v:
                continue
            out.append({
                "dataType": data_type,
                "data":     v,
                "tlp":      tlp,
                "ioc":      True,
                "message":  f"RECON-extracted {ioc_type}",
                "tags":     ["recon-auto-pushed", f"recon-type:{ioc_type}"],
            })
    return out


async def push_case(iocs: Dict[str, List[str]],
                    investigation: Dict[str, Any],
                    response_summary: Optional[Dict[str, Any]] = None,
                    raw_input: str = "",
                    config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Create a TheHive 5 case + attach observables. Returns
    {ok, case_id, case_number, url, observable_count, error}."""
    cfg = _config_or_none(config)
    if not cfg:
        return {"ok": False, "error": "TheHive not configured",
                "error_code": "not_configured"}

    try:
        tlp = max(0, min(3, int(cfg.get("THEHIVE_TLP", "2") or 2)))
    except (TypeError, ValueError):
        tlp = 2

    inv = investigation or {}
    rs  = response_summary or {}
    verdict = (rs.get("threat_level") or inv.get("verdict")
                or "UNKNOWN").upper()
    severity = _VERDICT_TO_SEVERITY.get(verdict, 1)
    actor    = ""
    raw_actor = inv.get("threat_actor")
    if isinstance(raw_actor, dict):
        actor = raw_actor.get("name") or raw_actor.get("group") or ""
    elif isinstance(raw_actor, str):
        actor = raw_actor

    title = (f"RECON {verdict}"
              + (f" — {actor}" if actor else "")
              + (f" — {raw_input[:80]}" if raw_input else ""))[:240]
    description_bits = [rs.get("summary") or "", "",
                        "## MITRE ATT&CK techniques observed:"]
    for t in (inv.get("mitre_techniques") or [])[:12]:
        description_bits.append(f"- {t}")
    description_bits += ["", "Generated by RECON (https://0xrecon.com)."]
    description = "\n".join(description_bits)[:4000]

    tags = ["recon-auto-pushed", f"recon-verdict:{verdict.lower()}"]
    for t in (inv.get("mitre_techniques") or [])[:6]:
        if isinstance(t, str):
            tid = t.split(" ", 1)[0].strip()
            if tid.upper().startswith("T"):
                tags.append(f"mitre-attack:{tid}")
    if actor:
        tags.append(f"recon-actor:{actor.lower().replace(' ', '-')}")

    base_url = cfg["THEHIVE_URL"].rstrip("/")
    headers = {
        "Authorization": f"Bearer {cfg['THEHIVE_KEY']}",
        "Content-Type":  "application/json",
        "User-Agent":    "RECON-ThreatIntel/1.0",
    }
    if cfg.get("THEHIVE_ORG"):
        headers["X-Organisation"] = cfg["THEHIVE_ORG"]

    import aiohttp
    timeout = aiohttp.ClientTimeout(total=20)
    async with aiohttp.ClientSession(timeout=timeout, headers=headers) as s:
        # 1) Create case
        case_payload = {
            "title":       title,
            "description": description,
            "severity":    severity,
            "tlp":         tlp,
            "pap":         tlp,   # PAP = Permissible Actions Protocol; default to TLP
            "tags":        tags[:20],
            "status":      "New",
        }
        try:
            async with s.post(f"{base_url}/api/v1/case",
                              json=case_payload) as r:
                if r.status >= 300:
                    body = await r.text()
                    return {"ok": False,
                            "error": f"TheHive case creation failed ({r.status}): {body[:240]}",
                            "error_code": "case_create_failed"}
                case_obj = await r.json()
        except Exception as e:
            return {"ok": False, "error": f"TheHive connect failed: {e}",
                    "error_code": "connect_failed"}

        case_id     = case_obj.get("_id") or case_obj.get("id")
        case_number = case_obj.get("number") or case_obj.get("caseNumber")
        if not case_id:
            return {"ok": False, "error": "TheHive returned no case ID",
                    "error_code": "unexpected_response"}

        # 2) Attach observables — TheHive accepts one per POST
        observables = _flatten_observables(iocs, tlp)
        attached = 0
        for obs in observables[:200]:
            try:
                async with s.post(f"{base_url}/api/v1/case/{case_id}/observable",
                                  json=obs) as r2:
                    if r2.status < 300:
                        attached += 1
            except Exception as e:
                _log.debug("thehive_push: observable failed: %s", e)

    return {
        "ok":               True,
        "case_id":          case_id,
        "case_number":      case_number,
        "url":              f"{base_url}/cases/{case_id}/details",
        "observable_count": attached,
        "verdict":          verdict,
        "severity":         severity,
    }
